# version: '3.8'

services:
  # --- FRONTEND (Next.js) ---
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      # Untuk Next.js: bisa baca ini di runtime
      - API_URL=http://localhost:3001
      # Kalau kamu pakai .env.local di dalam container, bisa tambah:
      # - NEXT_PUBLIC_API_URL=http://localhost:3001
    depends_on:
      - backend
    restart: unless-stopped

  # --- BACKEND (Hono.js) ---
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    environment:
      - DATABASE_DB: web_smkn6malang
      - DATABASE_USER: postgres
      - DATABASE_PASSWORD: 12345678
      - DATABASE_URL=postgres://user:pass@postgres:5432/sekolah_db
      - PORT=3001
      - NODE_ENV=production
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  # --- POSTGRESQL ---
  postgres:
    image: postgres:20-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: sekolah_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d sekolah_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

# --- VOLUMES ---
volumes:
  postgres-data: